-- PetFeet hosted PostgreSQL schema. DBConnection sets search_path to the isolated "petfeet" schema.
-- Applied once by DatabaseInitializer. Later startups preserve edits and deletions.

CREATE TABLE IF NOT EXISTS users (
  id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name               VARCHAR(100) NOT NULL,
  email              VARCHAR(150) NOT NULL UNIQUE,
  password           VARCHAR(255) NOT NULL,
  role               VARCHAR(20) NOT NULL CHECK (role IN ('ADMIN','SHELTER','ADOPTER')),
  phone              VARCHAR(20),
  address            VARCHAR(255),
  city               VARCHAR(80),
  preferred_species  VARCHAR(40),
  preferred_max_age  INTEGER,
  is_active          BOOLEAN NOT NULL DEFAULT TRUE,
  created_at         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS pets (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shelter_id   INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name         VARCHAR(80) NOT NULL,
  species      VARCHAR(40) NOT NULL,
  breed        VARCHAR(80) NOT NULL,
  age          INTEGER NOT NULL DEFAULT 0,
  gender       VARCHAR(10) NOT NULL CHECK (gender IN ('Male','Female')),
  location     VARCHAR(100) NOT NULL,
  description  TEXT,
  image_url    TEXT,
  status       VARCHAR(20) NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING','AVAILABLE','ADOPTED','REJECTED')),
  created_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_pet_status ON pets(status);
CREATE INDEX IF NOT EXISTS idx_pet_species ON pets(species);

CREATE TABLE IF NOT EXISTS adoption_applications (
  id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pet_id            INTEGER NOT NULL REFERENCES pets(id) ON DELETE CASCADE,
  adopter_id        INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  application_date  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  message           TEXT,
  status            VARCHAR(20) NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING','APPROVED','REJECTED','COMPLETED')),
  applicant_name    VARCHAR(100) NOT NULL,
  phone             VARCHAR(20) NOT NULL,
  email             VARCHAR(150) NOT NULL,
  address           VARCHAR(255) NOT NULL,
  reason            TEXT NOT NULL,
  experience        VARCHAR(255),
  home_type         VARCHAR(40),
  has_other_pets    BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE INDEX IF NOT EXISTS idx_app_status ON adoption_applications(status);

CREATE TABLE IF NOT EXISTS messages (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_id    INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  receiver_id  INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  message      TEXT NOT NULL,
  created_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  is_read      BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS notifications (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  message     VARCHAR(500) NOT NULL,
  is_read     BOOLEAN NOT NULL DEFAULT FALSE,
  created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS system_settings (
  setting_key    VARCHAR(60) PRIMARY KEY,
  setting_value  VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS adoption_history (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  application_id  INTEGER NOT NULL REFERENCES adoption_applications(id) ON DELETE CASCADE,
  pet_id          INTEGER NOT NULL REFERENCES pets(id) ON DELETE CASCADE,
  adopter_id      INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  shelter_id      INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  adopted_on      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS favorites (
  user_id     INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  pet_id      INTEGER NOT NULL REFERENCES pets(id) ON DELETE CASCADE,
  created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, pet_id)
);

CREATE TABLE IF NOT EXISTS activity_logs (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     INTEGER REFERENCES users(id) ON DELETE SET NULL,
  action      VARCHAR(255) NOT NULL,
  created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO users (id, name, email, password, role, phone, address, city, preferred_species, preferred_max_age) VALUES
 (1, 'PetFeet Admin',         'admin@petfeet.com',   '65536:UGV0RmVldFNhbHQyMDI2:RsroOYYCy+Qwyt+1Sz8or5R/z3IZuKYx2xqkVBL8BUk=', 'ADMIN',   '9000000001', 'PetFeet HQ, Knowledge Park III', 'Greater Noida', NULL, NULL),
 (2, 'Happy Tails Shelter',   'shelter@petfeet.com', '65536:UGV0RmVldFNhbHQyMDI2:RsroOYYCy+Qwyt+1Sz8or5R/z3IZuKYx2xqkVBL8BUk=', 'SHELTER', '9000000002', 'Sector 62', 'Greater Noida', NULL, NULL),
 (3, 'Paws & Whiskers Rescue','paws@petfeet.com',    '65536:UGV0RmVldFNhbHQyMDI2:RsroOYYCy+Qwyt+1Sz8or5R/z3IZuKYx2xqkVBL8BUk=', 'SHELTER', '9000000003', 'Lajpat Nagar', 'Delhi', NULL, NULL),
 (4, 'Noida Animal Care',     'care@petfeet.com',    '65536:UGV0RmVldFNhbHQyMDI2:RsroOYYCy+Qwyt+1Sz8or5R/z3IZuKYx2xqkVBL8BUk=', 'SHELTER', '9000000004', 'Sector 18', 'Noida', NULL, NULL),
 (5, 'Aarav Sharma',          'adopter@petfeet.com', '65536:UGV0RmVldFNhbHQyMDI2:RsroOYYCy+Qwyt+1Sz8or5R/z3IZuKYx2xqkVBL8BUk=', 'ADOPTER', '9000000005', 'B-12, Alpha 1', 'Greater Noida', 'Dog', 5),
 (6, 'Meera Iyer',            'meera@petfeet.com',   '65536:UGV0RmVldFNhbHQyMDI2:RsroOYYCy+Qwyt+1Sz8or5R/z3IZuKYx2xqkVBL8BUk=', 'ADOPTER', '9000000006', 'Sector 50', 'Noida', 'Cat', 3),
 (7, 'Kabir Singh',           'kabir@petfeet.com',   '65536:UGV0RmVldFNhbHQyMDI2:RsroOYYCy+Qwyt+1Sz8or5R/z3IZuKYx2xqkVBL8BUk=', 'ADOPTER', '9000000007', 'Indirapuram', 'Ghaziabad', 'Dog', 4)
ON CONFLICT (id) DO NOTHING;

INSERT INTO pets (id, shelter_id, name, species, breed, age, gender, location, description, image_url, status, created_at) VALUES
 (1, 2, 'Bruno',  'Dog', 'Golden Retriever', 2, 'Male',   'Greater Noida', 'Bruno is a gentle, sunny boy who loves fetch and belly rubs. Vaccinated, house-trained and great with kids.', 'images/pets/dog-golden.svg',   'AVAILABLE', CURRENT_TIMESTAMP - INTERVAL '20 days'),
 (2, 2, 'Luna',   'Dog', 'Labrador',         1, 'Female', 'Noida',         'Luna is a playful young Lab who adores water and long walks. She is still learning leash manners and learns fast.', 'images/pets/dog-labrador.svg', 'AVAILABLE', CURRENT_TIMESTAMP - INTERVAL '18 days'),
 (3, 3, 'Milo',   'Cat', 'Persian',          3, 'Male',   'Delhi',         'Milo is a calm, fluffy lap cat. He enjoys quiet evenings and needs regular brushing.', 'images/pets/cat-persian.svg',   'AVAILABLE', CURRENT_TIMESTAMP - INTERVAL '16 days'),
 (4, 3, 'Bella',  'Dog', 'Beagle',           4, 'Female', 'Ghaziabad',     'Bella is a curious Beagle with an amazing nose. Loves sniffing walks and is friendly with other dogs.', 'images/pets/dog-beagle.svg',    'AVAILABLE', CURRENT_TIMESTAMP - INTERVAL '15 days'),
 (5, 2, 'Max',    'Dog', 'German Shepherd',  5, 'Male',   'Greater Noida', 'Max is a loyal, well-trained German Shepherd. He has just found his forever family!', 'images/pets/dog-gsd.svg',       'ADOPTED',   CURRENT_TIMESTAMP - INTERVAL '40 days'),
 (6, 4, 'Coco',   'Dog', 'Indie Dog',        1, 'Female', 'Noida',         'Coco is a clever, street-smart Indie pup with endless energy. Indies are healthy, loyal and low maintenance.', 'images/pets/dog-indie.svg',    'AVAILABLE', CURRENT_TIMESTAMP - INTERVAL '12 days'),
 (7, 3, 'Simba',  'Cat', 'Siamese',          2, 'Male',   'Delhi',         'Simba is a chatty Siamese who will tell you all about his day. Very affectionate and loves to climb.', 'images/pets/cat-siamese.svg',   'AVAILABLE', CURRENT_TIMESTAMP - INTERVAL '11 days'),
 (8, 4, 'Daisy',  'Dog', 'Pomeranian',       3, 'Female', 'Gurugram',      'Daisy is a fluffy, confident Pom who loves attention. Perfect for apartment living.', 'images/pets/dog-pom.svg',       'AVAILABLE', CURRENT_TIMESTAMP - INTERVAL '9 days'),
 (9, 2, 'Rocky',  'Dog', 'Labrador',         6, 'Male',   'Greater Noida', 'Rocky is a calm senior Lab who just wants a soft bed and a gentle family. Senior pets make wonderful companions.', 'images/pets/dog-labrador.svg', 'AVAILABLE', CURRENT_TIMESTAMP - INTERVAL '8 days'),
 (10,4, 'Oreo',   'Cat', 'Indie Cat',        1, 'Female', 'Noida',         'Oreo is a black-and-white kitten who loves chasing shadows and curling up in laundry baskets.', 'images/pets/cat-indie.svg',     'AVAILABLE', CURRENT_TIMESTAMP - INTERVAL '6 days'),
 (11,3, 'Snowy',  'Rabbit','Holland Lop',    1, 'Female', 'Delhi',         'Snowy is a soft, quiet bunny who enjoys fresh greens and gentle cuddles.', 'images/pets/rabbit.svg',        'PENDING',   CURRENT_TIMESTAMP - INTERVAL '2 days'),
 (12,4, 'Pepper', 'Dog', 'Indie Dog',        0, 'Male',   'Ghaziabad',     'Pepper is a tiny rescue puppy found near a market. Dewormed and ready to be spoiled.', 'images/pets/dog-pepper.svg',    'PENDING',   CURRENT_TIMESTAMP - INTERVAL '1 day'),
 (13,2, 'Shadow', 'Cat', 'Domestic Shorthair',4,'Male',   'Greater Noida', 'Shadow is a shy black cat. Listing returned for a clearer photo (demo of the REJECTED status).', 'images/pets/cat-black.svg',    'REJECTED',  CURRENT_TIMESTAMP - INTERVAL '5 days')
ON CONFLICT (id) DO NOTHING;

INSERT INTO adoption_applications (id, pet_id, adopter_id, application_date, message, status, applicant_name, phone, email, address, reason, experience, home_type, has_other_pets) VALUES
 (1, 1, 5, CURRENT_TIMESTAMP - INTERVAL '3 days',  'We have a big garden and work from home.', 'PENDING',   'Aarav Sharma', '9000000005', 'adopter@petfeet.com', 'B-12, Alpha 1, Greater Noida', 'Looking for an active companion for our family.', 'Grew up with a Labrador', 'House with garden', FALSE),
 (2, 3, 5, CURRENT_TIMESTAMP - INTERVAL '2 days',  'Milo looks like a perfect fit.',          'PENDING',   'Aarav Sharma', '9000000005', 'adopter@petfeet.com', 'B-12, Alpha 1, Greater Noida', 'My mother wants a calm companion cat.', 'None', 'Apartment', FALSE),
 (3, 5, 6, CURRENT_TIMESTAMP - INTERVAL '30 days', 'Max would love our big terrace.',          'COMPLETED', 'Meera Iyer',   '9000000006', 'meera@petfeet.com',   'Sector 50, Noida', 'We lost our dog last year and are ready again.', '10 years with dogs', 'House with garden', FALSE),
 (4, 2, 6, CURRENT_TIMESTAMP - INTERVAL '4 days',  'Would Luna get along with a cat?',         'PENDING',   'Meera Iyer',   '9000000006', 'meera@petfeet.com',   'Sector 50, Noida', 'I would love a young dog to go jogging with.', 'Cats and dogs', 'Apartment', TRUE),
 (5, 4, 7, CURRENT_TIMESTAMP - INTERVAL '10 days', 'Bella seems lovely.',                      'REJECTED',  'Kabir Singh',  '9000000007', 'kabir@petfeet.com',   'Indirapuram, Ghaziabad', 'Want a pet for my kids.', 'None', 'Apartment', FALSE),
 (6, 7, 7, CURRENT_TIMESTAMP - INTERVAL '1 day',   'Simba sounds adorable!',                    'PENDING',   'Kabir Singh',  '9000000007', 'kabir@petfeet.com',   'Indirapuram, Ghaziabad', 'Kids love cats.', 'Had a cat as a child', 'Apartment', FALSE)
ON CONFLICT (id) DO NOTHING;

INSERT INTO adoption_history (id, application_id, pet_id, adopter_id, shelter_id, adopted_on) VALUES
 (1, 3, 5, 6, 2, CURRENT_TIMESTAMP - INTERVAL '28 days')
ON CONFLICT (id) DO NOTHING;

INSERT INTO messages (id, sender_id, receiver_id, message, created_at, is_read) VALUES
 (1, 5, 2, 'Hi! Is Bruno good with small children?', CURRENT_TIMESTAMP - INTERVAL '2 days', FALSE),
 (2, 2, 5, 'Hello Aarav! Yes, Bruno is great with kids. You are welcome to visit this weekend.', CURRENT_TIMESTAMP - INTERVAL '1 day', FALSE),
 (3, 6, 3, 'Hello, is Milo still available?', CURRENT_TIMESTAMP - INTERVAL '3 days', TRUE)
ON CONFLICT (id) DO NOTHING;

INSERT INTO notifications (id, user_id, message, is_read, created_at) VALUES
 (1, 2, 'New adoption application received for Bruno.', FALSE, CURRENT_TIMESTAMP - INTERVAL '3 days'),
 (2, 5, 'Welcome to PetFeet! Browse pets and find your new friend.', FALSE, CURRENT_TIMESTAMP - INTERVAL '5 days'),
 (3, 6, 'Congratulations! Your adoption of Max is complete.', TRUE, CURRENT_TIMESTAMP - INTERVAL '28 days'),
 (4, 7, 'Your application for Bella was not approved this time.', FALSE, CURRENT_TIMESTAMP - INTERVAL '9 days'),
 (5, 1, 'Pet listing "Snowy" is waiting for approval.', FALSE, CURRENT_TIMESTAMP - INTERVAL '2 days')
ON CONFLICT (id) DO NOTHING;

INSERT INTO favorites (user_id, pet_id) VALUES (5, 1), (5, 6), (6, 3), (7, 8)
ON CONFLICT (user_id, pet_id) DO NOTHING;

INSERT INTO system_settings (setting_key, setting_value) VALUES
 ('site_name', 'PetFeet'),
 ('contact_email', 'hello@petfeet.com'),
 ('allow_registration', 'true'),
 ('require_pet_approval', 'true'),
 ('max_active_applications', '5')
ON CONFLICT (setting_key) DO NOTHING;

INSERT INTO activity_logs (id, user_id, action, created_at) VALUES
 (1, 1, 'System initialised with demo data', CURRENT_TIMESTAMP - INTERVAL '30 days'),
 (2, 2, 'Listed pet Bruno', CURRENT_TIMESTAMP - INTERVAL '20 days'),
 (3, 6, 'Adoption completed for Max', CURRENT_TIMESTAMP - INTERVAL '28 days')
ON CONFLICT (id) DO NOTHING;

-- Keep identity sequences ahead of any explicitly seeded IDs.
SELECT setval(pg_get_serial_sequence('users','id'), GREATEST((SELECT COALESCE(MAX(id),1) FROM users),1), true);
SELECT setval(pg_get_serial_sequence('pets','id'), GREATEST((SELECT COALESCE(MAX(id),1) FROM pets),1), true);
SELECT setval(pg_get_serial_sequence('adoption_applications','id'), GREATEST((SELECT COALESCE(MAX(id),1) FROM adoption_applications),1), true);
SELECT setval(pg_get_serial_sequence('messages','id'), GREATEST((SELECT COALESCE(MAX(id),1) FROM messages),1), true);
SELECT setval(pg_get_serial_sequence('notifications','id'), GREATEST((SELECT COALESCE(MAX(id),1) FROM notifications),1), true);
SELECT setval(pg_get_serial_sequence('adoption_history','id'), GREATEST((SELECT COALESCE(MAX(id),1) FROM adoption_history),1), true);
SELECT setval(pg_get_serial_sequence('activity_logs','id'), GREATEST((SELECT COALESCE(MAX(id),1) FROM activity_logs),1), true);
