<%@ include file="/WEB-INF/views/common/taglibs.jspf" %>
<c:set var="pageTitle" value="About Project / Java Concepts"/>
<%@ include file="/WEB-INF/views/common/header.jspf" %>
<section class="section" style="padding-top:44px"><div class="container" style="max-width:1000px">
  <h1>About Project / Java Concepts</h1>
  <p class="muted">Viva guide: every concept the rubric asks for, and exactly where it lives in the PetFeet source code (<code>src/main/java/com/petfeet/...</code>).</p>

  <div class="grid grid-3 mt-2">
    <div class="card card-pad"><h3>Technology</h3><p class="small mb-0">Java 11 &middot; Servlets 4.0 &middot; JSP + JSTL &middot; JDBC &middot; MySQL &middot; Maven (WAR) &middot; HTML5/CSS3/JavaScript</p></div>
    <div class="card card-pad"><h3>Database <code>petfeet_db</code></h3><p class="small mb-0">users &middot; pets &middot; adoption_applications &middot; messages &middot; notifications &middot; system_settings &middot; adoption_history &middot; favorites &middot; activity_logs</p></div>
    <div class="card card-pad"><h3>Packages</h3><p class="small mb-0"><code>model</code> &middot; <code>dao</code> &middot; <code>service</code> &middot; <code>servlet</code> &middot; <code>filter</code> &middot; <code>listener</code> &middot; <code>util</code> &middot; <code>exception</code></p></div>
  </div>

  <h2 class="mt-3">MVC request flow</h2>
  <div class="card card-pad"><p class="mb-0"><b>Browser</b> &rarr; <b>Filter</b> (<code>CsrfFilter</code>, <code>AuthFilter</code>) &rarr; <b>Controller</b> = Servlet (<code>LoginServlet</code>, <code>AddPetServlet</code> ...) &rarr; <b>Service</b> (business rules, transactions) &rarr; <b>DAO</b> (JDBC + MySQL) &rarr; <b>Model</b> objects &rarr; Servlet puts data in the request &rarr; <b>View</b> = JSP under <code>WEB-INF/views</code> (not reachable directly, so every page must pass through a controller).</p></div>

  <h2 class="mt-3">Concept checklist</h2>
  <div class="card">
    <div class="concept"><h3>OOP</h3><p>Classes and objects for every entity: <code>User</code>, <code>Pet</code>, <code>AdoptionApplication</code>, <code>Message</code>, <code>Notification</code>. Constructors e.g. <code>Notification(int, String)</code>, <code>Shelter(name, email, phone)</code>. Private fields + getters/setters = <b>encapsulation</b>.</p></div>
    <div class="concept"><h3>Inheritance</h3><p><code>User</code> &rarr; <code>Admin</code>, <code>Shelter</code>, <code>Adopter</code>. Also <code>BaseServlet</code> &rarr; all 28 servlets, <code>BaseDAO</code> &rarr; every DAO, <code>PetFeetException</code> &rarr; <code>ValidationException</code>, <code>DatabaseException</code> etc.</p></div>
    <div class="concept"><h3>Polymorphism</h3><p><code>UserDAO</code> returns a <code>User</code> reference that is really an Admin/Shelter/Adopter; <code>user.getDashboardPath()</code> behaves differently per role. <code>NotificationService</code> has two implementations (<code>DbNotificationService</code> immediate, <code>QueuedNotificationService</code> background) and <code>MessageServiceImpl</code> works with either.</p></div>
    <div class="concept"><h3>Abstraction</h3><p>Abstract class <code>User</code> with abstract <code>getRole()</code>, <code>getDashboardPath()</code>, <code>getCapabilities()</code>; abstract <code>BaseDAO</code> and <code>BaseServlet</code> hide JDBC / lifecycle plumbing.</p></div>
    <div class="concept"><h3>Interfaces</h3><p><code>CRUDOperations&lt;T, ID&gt;</code> (implemented by all DAOs), <code>NotificationService</code>, <code>MessageService</code>, functional interface <code>BaseDAO.RowMapper&lt;T&gt;</code> (used with lambdas), <code>Runnable</code> for the workers.</p></div>
    <div class="concept"><h3>Method overriding</h3><p><code>getRole()</code> / <code>getDashboardPath()</code> in each user subclass, <code>toString()</code>, <code>BaseServlet.init()/service()/destroy()</code>, <code>doGet()/doPost()</code> in servlets, <code>run()</code> in workers.</p></div>
    <div class="concept"><h3>Exception handling</h3><p>Custom checked exception hierarchy in <code>com.petfeet.exception</code>. DAOs wrap <code>SQLException</code> in <code>DatabaseException</code>; <code>BaseServlet.friendlyMessage()</code> shows safe text; <code>web.xml</code> routes errors to the "Oops! This paw went missing." page.</p></div>
    <div class="concept"><h3>Collections</h3><p><code>List&lt;Pet&gt;</code> search results, <code>Set&lt;Integer&gt;</code> favourite ids (<code>HashSet</code>), <code>Map&lt;String,Long&gt;</code> statistics (<code>LinkedHashMap</code>), <code>HashMap</code> affinity scores in the recommendation engine, <code>Queue</code> (<code>LinkedList</code>) in <code>NotificationQueue</code>.</p></div>
    <div class="concept"><h3>Generics</h3><p><code>CRUDOperations&lt;T, ID&gt;</code>, <code>RowMapper&lt;T&gt;</code>, generic helper <code>&lt;T&gt; List&lt;T&gt; queryList(...)</code> in <code>BaseDAO</code>, typed collections everywhere.</p></div>
    <div class="concept"><h3>Multithreading</h3><p>Two background threads started by <code>AppLifecycleListener</code> through <code>BackgroundServiceManager</code>: <code>NotificationWorker</code> (delivers queued notifications) and <code>StatisticsWorker</code> (refreshes admin statistics every 15 s). See <b>Background Services</b> in the admin dashboard.</p></div>
    <div class="concept"><h3>Synchronization</h3><p><code>NotificationQueue</code> uses <code>synchronized</code> + <code>wait()/notifyAll()</code> (producer/consumer), <code>StatsCache</code> and <code>BackgroundStatus</code> use synchronized methods, <code>BaseServlet</code> counts requests with <code>AtomicLong</code>, the worker stop flag is <code>volatile</code>.</p></div>
    <div class="concept"><h3>JDBC</h3><p><code>DBConnection</code> (<code>DriverManager.getConnection</code>, settings in <code>db.properties</code>) and <code>BaseDAO</code> (<code>Connection</code>, <code>PreparedStatement</code>, <code>ResultSet</code> inside try-with-resources).</p></div>
    <div class="concept"><h3>CRUD</h3><p>Users: <code>UserManagementServlet</code> &rarr; <code>UserService</code> &rarr; <code>UserDAO</code>. Pets: <code>AddPetServlet</code>, <code>UpdatePetServlet</code>, <code>DeletePetServlet</code> &rarr; <code>PetService</code> &rarr; <code>PetDAO</code>. Messages and notifications have create / read / update / delete too.</p></div>
    <div class="concept"><h3>PreparedStatement</h3><p>Every query binds user input with <code>?</code> placeholders (see <code>BaseDAO.bind</code>), including the dynamic filter query in <code>PetDAO.search()</code> &mdash; this prevents SQL injection.</p></div>
    <div class="concept"><h3>Transactions</h3><p><code>AdoptionService.approve()</code>: <code>setAutoCommit(false)</code> &rarr; update application &rarr; set pet ADOPTED &rarr; insert <code>adoption_history</code> &rarr; create notifications &rarr; <code>commit()</code>; any failure triggers <code>rollback()</code>. <code>reject()</code> is transactional too.</p></div>
    <div class="concept"><h3>Servlets</h3><p>28 servlets using <code>@WebServlet</code>, <code>doGet</code>/<code>doPost</code> and the post/redirect/get pattern. Lifecycle: <code>init()</code>, <code>service()</code>, <code>destroy()</code> are logged in <code>BaseServlet</code> (check the Tomcat log).</p></div>
    <div class="concept"><h3>Session management</h3><p><code>LoginServlet</code> creates the <code>HttpSession</code> (user, role), regenerates the session id, sets a 30 min timeout; <code>AuthFilter</code> blocks anonymous users and wrong roles; <code>LogoutServlet</code> calls <code>session.invalidate()</code>. A <code>CsrfFilter</code> adds a per-session token to every POST.</p></div>
    <div class="concept"><h3>MVC architecture</h3><p>Model = <code>model</code> + <code>dao</code> + <code>service</code>, View = JSP files in <code>WEB-INF/views</code>, Controller = servlets in <code>servlet</code>.</p></div>
  </div>
  <p class="muted small mt-2">Extra features: favourites, pet comparison, rule-based "Pets you may love" (<code>PetService.recommend</code>), application progress tracker, notifications bell, search suggestions, image upload, activity log, system settings that really change behaviour.</p>
</div></section>
<%@ include file="/WEB-INF/views/common/footer.jspf" %>
